### PR TITLE
fix #45: issue with help text on the summary proposal page

### LINKED ISSUE #45: [bug] issue with help text on the summary proposal page
image-issue

The issue is the amount you get for $100 USDC at $5 per META. It should be 20 META.

### PR DESCRIPTION
**Pull request by decartesol**
When betting w/ 100 META
Screenshot 2023-11-24 at 8 54 53 AM

When betting w/ 100 USDC
Screenshot 2023-11-24 at 8 55 45 AM

### CODE REVIEW

**Comment by decartesol** [comment]
#45

**Comment by R-K-H** [comment]
LGTM! Thanks.

**Comment by R-K-H** [comment]
@decartesol looks like your linting isn't respecting the line length. Could you reduce the line length of your 256 and 262? See the build details for more info you need to.

**Comment by R-K-H** [comment]
Still erroring - 266:49  Error: Trailing spaces not allowed.  no-trailing-spaces

**Comment by decartesol** [comment]
@R-K-H pls run the workflow again

**Pull request merged**
